import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import imageCompression from 'browser-image-compression'
import { InputHTMLAttributes, useState } from 'react'
import { Box } from '@mui/system'
import { Button } from '@mui/material'



const Home: NextPage = () => {
  const [originalImage, setOriginalImage] = useState<string>()
  const [originalImageFile, setOriginalImageFile] = useState("")
  const [compressedImage, setCompressedImage] = useState<string>()
  const [fileName, setFileName] = useState("")

  function handleImage (e : any) {
  const imageFile = e.target.files[0]
  setOriginalImage(imageFile)
  setOriginalImageFile(URL.createObjectURL(imageFile))
  setFileName(imageFile.name)
}


  const handleCompressImage = (e:any) => {
    e.preventDefault()
    const options = {
      maxSizeMB:1,
      maxWidthOrHeight: 500,
      useWebWorker: true
    }

    /*if(options.maxSizeMB >= originalImage/1024) {

    }*/
    let output
    imageCompression(originalImage, options).then((d)=>{
      output = d
      const downloadLink = URL.createObjectURL(output)
      setCompressedImage(downloadLink)

    })

  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{display: "flex"}}>
        <div style={{width:"400px", height: "200px"}}><img src={originalImageFile ? originalImageFile : "/images/IMG_4029.jpeg"} alt="" style={{height: "100%"}}/></div>
        <div>
          <input type="file" accept="/image/*" onChange={handleImage} />
          <hr />
          {originalImageFile && <Button onClick={(e)=>{handleCompressImage(e)}}>compress</Button>}
          <hr />
          {compressedImage && <a href={compressedImage} download={fileName}><Button onClick={()=>{}}>download</Button></a>}
        </div>
        <div style={{width:"400px", height: "200px"}}><img src={compressedImage ? compressedImage : "/images/IMG_4029.jpeg"} alt="" style={{height: "100%"}}/></div>
      </main>

      <footer>
      </footer>
    </div>
  )
}

export default Home
